on: [push]

name: CI

jobs:
  test_action:
    runs-on: self-hosted
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: TestPackage
        uses: ./
        with:
          filename: test.sopm
