on: [push]

name: CI

jobs:
  test_action:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: TestPackage
        uses: ./
        with:
          filename: test.sopm
